# Generated by Django 5.1.2 on 2024-11-11 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='openai_api_key',
            new_name='api_key',
        ),
    ]
